# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

users1 = User.create(first_name: "Amit", last_name: "Joshi", user_name: "wannamit", email: "wannamit@gmail.com", gender: "m", password: "aafter18", password_confirmation: "aafter18")
users2 = User.create(first_name: "Sneha", last_name: "Neupane", user_name: "chari", email: "elrosa.sneha@gmail.com", gender: "f", password: "aafter18", password_confirmation: "aafter18")
users3 = User.create(first_name: "Nirdosh", last_name: "Gautam", user_name: "nirdosh17", email: "nrgt.gtm@gmail.com", gender: "m", password: "aafter18", password_confirmation: "aafter18")
users3 = User.create(first_name: "Iksya", last_name: "Gurung", user_name: "xha.grg", email: "xha.grg@cloudfactory.com", gender: "m", password: "aafter18", password_confirmation: "aafter18")
users3 = User.create(first_name: "Karmath", last_name: "Dangol", user_name: "karmath", email: "katmath@cloudfactory.com", gender: "m", password: "aafter18", password_confirmation: "aafter18")

debates0 = Debate.create(topic: "Nepal Earthquake can be taken as positive for nepal.", description: "It will help to re-built Neapl from ground in a well managed environment.", user_id: 1)
debates1 = Debate.create(topic: "#NepalNeeds data is useless.", description: "The so called public data provided by government in #NepalNeeds google doc doesnt seem trusty. \n link: https://docs.google.com/spreadsheets/d/1FbeHrQsLy5TlrFlVz1obHYyLVji6XscPTH2Yo0ryahE", user_id: 1)
debates2 = Debate.create(topic: "PM Relief Fund is not transparent.", description: "Even with publicly shown data there is still large number of undocumended incoming fund. \n Link: https://docs.google.com/spreadsheets/d/1Q3QSx1_p78T4_qo_JVj5vEQtzuCFWP2AfxYnVBSNzLQ", user_id: 1)
debates3 = Debate.create(topic: "Nepal Constitution will never be given to us.", description: "When will these politician be serious about constitution. Aint its our time to raise against them?", user_id: 2)
debates4 = Debate.create(topic: "Indian involvment in nepal politics is ruinig nepal.", description: "Nepali politician should understand that depending on India will eventually harm themself and in return to whone Nepal.", user_id: 3)
debates5 = Debate.create(topic: "Trial Topic 1", description: "This is description of Trial Topic 1.", user_id: 2)
debates6 = Debate.create(topic: "Trial Topic 2", description: "This is description of Trial Topic 2.", user_id: 3)
debates7 = Debate.create(topic: "Trial Topic 3", description: "This is description of Trial Topic 3.", user_id: 3)
debates8 = Debate.create(topic: "Trial Topic 4", description: "This is description of Trial Topic 4.", user_id: 1)
debates9 = Debate.create(topic: "Trial Topic 5", description: "This is description of Trial Topic 5.", user_id: 2)

comments0 = Comment.create(description: "We can do sustation development.", user_id:2 , debate_id:1 , tag: true)
comments1 = Comment.create(description: "It will help remap structure of kathmandu as per metropolitan city.", user_id:1 , debate_id:1 , tag: true)
comments2 = Comment.create(description: "Everything is destroyed. How can it be positive?", user_id:3 , debate_id:1 , tag: false)
comments3 = Comment.create(description: "Positive in the sense that it could be taken as opportunity for proper development.", user_id:1 , debate_id:1 , tag: true)
comments4 = Comment.create(description: "With that much of death troll and economic push back, this will alwzys be black day for Nepal.", user_id:4 , debate_id:1 , tag: false)
comments5 = Comment.create(description: "For effected ones data cant do anythng rather provide support.", user_id:5 , debate_id:2 , tag: true)
comments6 = Comment.create(description: "With this data we can organize the support distribution process.", user_id:2 , debate_id:2 , tag: false)
comments7 = Comment.create(description: "Proper analysis of data will help to get info of which part is more effected and provide help to then at first.", user_id:4 , debate_id:2 , tag: false)
comments8 = Comment.create(description: "In this time of immediate need for help who have time to analyze data, more its not even verified.", user_id:1 , debate_id:2 , tag: true)
comments9 = Comment.create(description: "Yes indeed.", user_id:2 , debate_id:3 , tag: true)
comments10 = Comment.create(description: "Every support and fund provided is handled well, no misuse at all.", user_id:4 , debate_id:3 , tag: false)
comments11 = Comment.create(description: "The initial amount and incoming fund amount addition should have been greater than current amount.", user_id:5 , debate_id:3 , tag: true)
comments12 = Comment.create(description: "PM can use it as he wants, who is there to monitor him?", user_id:1 , debate_id:3 , tag: true)
comments13 = Comment.create(description: "PMRF is not controlled by PM himself. its just name. He has no authority to access it.", user_id:4 , debate_id:3 , tag: false)
comments14 = Comment.create(description: "Trial Comment 1", user_id:3 , debate_id:4 , tag: true)
comments15 = Comment.create(description: "Trial Comment 2", user_id:4 , debate_id:4 , tag: true)
comments16 = Comment.create(description: "Trial Comment 3", user_id:5 , debate_id:5 , tag: false)
comments17 = Comment.create(description: "Trial Comment 4", user_id:1 , debate_id:6 , tag: true)
comments18 = Comment.create(description: "Trial Comment 5", user_id:2 , debate_id:7 , tag: true)
comments19 = Comment.create(description: "Trial Comment 6", user_id:3 , debate_id:7 , tag: false)

likes = Like.create(user_id: 1, debate_id: 2)
likes = Like.create(user_id: 2, debate_id: 2)
likes = Like.create(user_id: 3, debate_id: 2)
likes = Like.create(user_id: 4, debate_id: 2)
likes = Like.create(user_id: 5, debate_id: 2)
likes = Like.create(user_id: 1, debate_id: 1)
likes = Like.create(user_id: 2, debate_id: 1)
likes = Like.create(user_id: 3, debate_id: 1)
likes = Like.create(user_id: 1, debate_id: 3)
likes = Like.create(user_id: 4, debate_id: 3)
likes = Like.create(user_id: 5, debate_id: 3)
likes = Like.create(user_id: 2, debate_id: 3)
likes = Like.create(user_id: 2, debate_id: 4)
likes = Like.create(user_id: 4, debate_id: 5)
likes = Like.create(user_id: 5, debate_id: 5)
likes = Like.create(user_id: 1, debate_id: 6)
likes = Like.create(user_id: 3, debate_id: 6)
likes = Like.create(user_id: 2, debate_id: 9)
likes = Like.create(user_id: 5, debate_id: 9)
likes = Like.create(user_id: 4, debate_id: 9)
likes = Like.create(user_id: 4, debate_id: 10)
likes = Like.create(user_id: 5, debate_id: 10)